# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buton1 = QtWidgets.QPushButton(self.centralwidget)
        self.buton1.setGeometry(QtCore.QRect(130, 330, 131, 28))
        self.buton1.setObjectName("buton1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label2.setObjectName("label2")
        self.line1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(120, 40, 151, 22))
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(120, 100, 151, 22))
        self.line2.setObjectName("line2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(30, 156, 71, 20))
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(30, 220, 81, 16))
        self.label4.setObjectName("label4")
        self.line4 = QtWidgets.QLineEdit(self.centralwidget)
        self.line4.setGeometry(QtCore.QRect(120, 220, 151, 22))
        self.line4.setObjectName("line4")
        self.line3 = QtWidgets.QLineEdit(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(120, 160, 151, 22))
        self.line3.setObjectName("line3")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(30, 280, 55, 16))
        self.label5.setObjectName("label5")
        self.line5 = QtWidgets.QLineEdit(self.centralwidget)
        self.line5.setGeometry(QtCore.QRect(120, 280, 151, 22))
        self.line5.setObjectName("line5")
        self.tbl1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl1.setGeometry(QtCore.QRect(340, 30, 691, 271))
        self.tbl1.setRowCount(20)
        self.tbl1.setColumnCount(5)
        self.tbl1.setObjectName("tbl1")
        self.buton2 = QtWidgets.QPushButton(self.centralwidget)
        self.buton2.setGeometry(QtCore.QRect(820, 330, 131, 28))
        self.buton2.setObjectName("buton2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buton1.setText(_translate("MainWindow", "KAYIT OL"))
        self.label1.setText(_translate("MainWindow", "İsim"))
        self.label2.setText(_translate("MainWindow", "Soyisim"))
        self.label3.setText(_translate("MainWindow", "Mail"))
        self.label4.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.label5.setText(_translate("MainWindow", "Şifre"))
        self.buton2.setText(_translate("MainWindow", "SİL"))
